### PR TITLE
update examples to latest aframe and use open-easyrtc

### PR DESCRIPTION
**Pull request by vincentfretin**
First some context, we currently have the original repository https://github.com/networked-aframe/networked-aframe that doesn't have a maintainer anymore (so doing a PR there will probably not be merged because Hayden Lee's new job doesn't legally allow him to work on other projects, @haydenjameslee correct me if I'm wrong) and Mozilla's fork that is used with Hubs and dialog adapter that is inside Hubs repository.

Some history, the two repositories https://github.com/networked-aframe/networked-aframe and https://github.com/MozillaReality/networked-aframe were in sync around Jul 24, 2019.
Since then, in the Mozilla fork, there were many fixes about persistent, ownership and received data checks.
In the original repo, there was at one point a PR to update it to open-easyrtc, but Hayden Lee didn't merge it because he was working on new adapters that are now webrtc and socketio, without any other external dependency except socket.io.
The socketio doesn't support audio, the webrtc adapter is not battle tested and seems currently broken.
The easyrtc adapter code was moved to a separate repo https://github.com/networked-aframe/naf-easyrtc-adapter but no release was made.
In the meantime, new people want to try to tinker with NAF (see #networked-aframe channel on A-Frame Slack) but we don't currently have an up to date repo with latest aframe examples and a simple working adapter, this is sad. :(

So I made this PR again Mozilla's fork master branch with a subset of the changes that Hayden did in the original repo plus some more fixes with latest aframe compatibility he didn't catch and the switch to open-easyrtc for security reasons.
I didn't backport all the packages updates and eslint changes so Mozilla can merge the PR without too much review, it's mainly doc changes. I hope you can merge it.

### CODE REVIEW

**Comment by kylebakerio** [comment]
Just wanted to add that this all looks very similar to changes I've tried and seen working well in my own fork of the NAF 0.7.1 code. I've been using an open-easyrtc updated fork of the adapter, which works well and is certainly an upgrade. The fixes and updates look very much needed, and it would be great to have this become the new 'default' version of NAF in one place for people to use. 

Vincent is also very competent with NAF and in general, and the changes are all pretty straightforward.

Hope this pull gets accepted!

**Comment by arpu** [comment]
i still think best would be to get this done in the  https://github.com/networked-aframe repo

**Comment by kylebakerio** [comment]
@arpu that's not an option, hayden has abandoned it. he hasn't appointed a maintainer. It's been 6 months. Why would it be better anyways? Even if he returned, frankly, it seems like the mozilla branch has fixes that that repo needs and it isn't ideal to have two separate forks.

**Comment by arpu** [comment]
any statement from @haydenjameslee on this?

**Comment by kylebakerio** [comment]
He emailed a few months ago that he was considering new maintainers. Then he never emailed anyone again. I emailed a check in a month or two ago asking as a gentle reminder, no response. He's expressed that he thinks the repo doesn't have value and shouldn't be used anyways, and he's also mentioned he's at a new job where he's not allowed to contribute. He's essentially AWOL.

**Comment by vincentfretin** [comment]
Here is his statement:
https://aframevr.slack.com/archives/C65MC3NSF/p1596767155313800
I did a screenshot before the comments are lost.
Capture d’écran de 2021-01-14 13-33-02

**Comment by robertlong** [comment]
@vincentfretin I don't think we want to maintain the de-facto networked-aframe repo. This repo already has some modifications specific to Hubs and in the future we plan on diverging even more. There's already a [networked-aframe](https://github.com/orgs/networked-aframe) organization. @haydenjameslee and I are the only members, perhaps you or someone else from the community could be added to the org and act as the new maintainers? You'd have to reach out to Hayden and see if he is comfortable with that. You can always pull changes from this repo, we just can't guarantee compatibility with AFrame projects outside of Hubs.

**Comment by vincentfretin** [comment]
Thank you @robertlong for your reply so we can now try to move things forward.
FYI all current changes in Mozilla's fork are ok outside of Hubs, me and others are using it. But I hear you that maybe in the future there may be a breaking change in the way we won't be able to use it outside of Hubs.
Maintaining the project in the networked-aframe organization would be the thing to do yes. I think @kylebakerio contacted @haydenjameslee a while ago but he didn't have a reply. What we would need is for me @vincentfretin and @kylebakerio to be members of the organization, and also have the possibility to make releases to npmjs.com
I could create a PR on the original repo to get all the latest good changes of the Mozilla's fork.
I don't want to commit to maintain the new "webrtc" adapter there though, that is too new and seems to have several issues. @kylebakerio could maintain the extracted easyrtc adapter that is now in the external repo https://github.com/networked-aframe/naf-easyrtc-adapter and he was willing to add video sharing too. I can help him as well, but I don't use easyrtc myself.
I'm currently maintaining a version of naf-janus-adapter here
https://github.com/Synantoo/naf-janus-adapter/tree/3.0.x and @arpu will be using it too.

If we don't hear back from @haydenjameslee in the coming weeks, I think in this case @kylebakerio and me will start a third fork based on Mozilla's fork, it will be just easier.

**Comment by vincentfretin** [comment]
I sent an email to @haydenjameslee with the link to this discussion.

**Comment by vincentfretin** [comment]
For those wanting to run the updated examples in this PR.
You can clone this PR like this:
```
git clone -b update-examples git@github.com:vincentfretin/networked-aframe.git
```

`vincentfretin/networked-aframe` is initially a fork of the original repo, but my `updated-examples` branch is actually based from mozilla's master.

**Comment by vincentfretin** [comment]
@haydenjameslee gave me the Admin role on the networked-aframe repo so I can keep the flame going like he said ;-)
@kylebakerio I added you with Admin role as well to be co-maintainer with me. :-)
We can start merging some PR and creating issues there.

**Comment by vincentfretin** [comment]
You can now go back to https://github.com/networked-aframe/networked-aframe master, it contains all the fixes of mozilla's fork and the easyrtc adapter is back with open-easyrtc.

**Comment by kylebakerio** [comment]
exciting news!

**Pull request closed without merging**
